name: Flujo_trabajo # nombre del flujo de trabajo
# evento que activa el flujo de trabajo 
on:
  push:
    branches:
      - main
# El flujo se ejecutará cada vez que haya un push (es decir, una actualización o un nuevo commit) a la rama main.
# configuración del trabajo
jobs:
  # Identificador del trabajo (job) dentro del flujo de trabajo.
  example-job:
    # El job se ejecutará en un runner con el sistema operativo Ubuntu en su última versión.
    runs-on: ubuntu-latest
    # Pasos del job
    steps:
      # Checkout del código
      - name: Checkout code
        uses: actions/checkout@v3
        # Este paso utiliza la acción oficial actions/checkout en su versión 3.
        # Clona el código fuente del repositorio en el runner para que pueda ser utilizado por otros pasos.
      
      - name: Use GITHUB_TOKEN
        # Ejecuta el comando curl para realizar una llamada a la API de GitHub.
        run: |
          curl -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
        # GITHUB_TOKEN se genera automáticamente para cada ejecución del flujo y tiene permisos predeterminados para interactuar con el repositorio.
                 -H "Accept: application/vnd.github.v3+json" \
        # versión 3 de la API de GitHub.
                 https://api.github.com/repos/${{ github.repository }}
        # Es una variable de contexto de GitHub que contiene el nombre del repositorio en formato owner/repo
